/*
	* Generated by MybatisGenerator on 2016-07-15 10:50:34
*/
package org.jigang.entity;

import java.util.Date;

/** 
 * entity for table test.account
 */
public class Account {
	private Integer id;

	private Integer merchantId;

	private String accountName;

	private String accountPwd;

	private Date lastLoginTime;

	private Integer state;

	private Date createTime;

	private Date updateTime;


	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getMerchantId() {
		return this.merchantId;
	}

	public void setMerchantId(Integer merchantId) {
		this.merchantId = merchantId;
	}

	public String getAccountName() {
		return this.accountName;
	}

	public void setAccountName(String accountName) {
		this.accountName = accountName;
	}

	public String getAccountPwd() {
		return this.accountPwd;
	}

	public void setAccountPwd(String accountPwd) {
		this.accountPwd = accountPwd;
	}

	public Date getLastLoginTime() {
		return this.lastLoginTime;
	}

	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

	public Integer getState() {
		return this.state;
	}

	public void setState(Integer state) {
		this.state = state;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}


	public String toString() {
		return "id = " + this.id + ", merchantId = " + this.merchantId
			+ ", accountName = " + this.accountName + ", accountPwd = " + this.accountPwd
			+ ", lastLoginTime = " + this.lastLoginTime + ", state = " + this.state
			+ ", createTime = " + this.createTime + ", updateTime = " + this.updateTime;
	}
}